server:
  port: 80

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/his_java1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8

mybatis:
  type-aliases-package: com.neuedu.entity
  #告诉mybatis的所有Mapper文件的位置
  mapperLocations:  classpath:com/neuedu/mapper/*.xml


#mapper:
#  mappers:
#    - tk.mybatis.springboot.util.MyMapper
#  not-empty: false
#  identity: MYSQL

# 配置PageHelper插件
# https://github.com/pagehelper/Mybatis-PageHelper/blob/master/README_zh.md
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


debug: true